// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kepkwspzjqckqmeihmfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtlcGt3c3B6anFja3FtZWlobWZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1NjYyMDIsImV4cCI6MjA2NjE0MjIwMn0.5pdLy_N0TkxIFnawMnYxWDOm6X8ZFxPyJqFtuNPL640";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);